Repository OS03Bit/IntelliCampus, pull requests merged in 2023-07, with the labels that each got.

#84 v0.19.4: Add Program and Add Department routes and controller created
  assets/css/admin-addDept.css
  assets/css/admin-addProgram.css
  assets/css/admin-noty.css
  assets/css/teach-note-popup.css
  assets/scss/addProgram.css
  assets/scss/admin-addDept.scss
  assets/scss/admin-addProgram.scss
  assets/scss/admin-noty.scss
  assets/scss/teach-note-popup.scss
  controllers/admin_controller.js
  routes/admins.js
  views/admin/addDepartment.ejs
  views/admin/addDepartment.html
  views/admin/addProgram.ejs
  views/admin/addProgram.html
  views/admin/addstudent.ejs
  views/admin/create_notification.ejs
  views/teacher/subject/notes.ejs
Labels: Page Added

#85 v0.20.1: Teacher Assignment Check Page Added
  assets/css/addteacher.css
  assets/css/error.css
  assets/css/teach-assign-check.css
  assets/images/clock.png
  assets/scss/teach-assign-check.scss
  controllers/teacher_controller.js
  routes/teachers.js
  upload/tg/TGward-1689281487194-template_tg.xlsx
  views/teacher/subject/assignment_check.ejs
  views/teacher/subject/attendance-add.ejs
  views/template/page.html
Labels: Page Added

#86 v0.20.2: Spotlight Search created
  assets/css/admin-dash.css
  assets/css/teach-note-popup.css
  assets/scss/admin-dash.scss
  controllers/teacher_controller.js
  routes/teachers.js
  views/admin/dashboard.ejs
  views/teacher/subject/assignment_check.ejs
  views/teacher/subject/attendance-add.ejs
  views/teacher/subject/attendance-update.ejs
  views/teacher/subject/attendance-view.ejs
  views/teacher/subject/attendanceviewsingle.ejs
  views/teacher/subject/internalmarks.ejs
Labels: Feature Added

#89 v0.21.2: Js name Updated
  assets/js/admin-addteach.js
  assets/js/admin-allotsub.js
  assets/js/dash-cale.js
  assets/js/internalMarks.js
  assets/js/notification_form.js
  assets/js/noty.js
  assets/js/std-att-select.js
  assets/js/std-feedback.js
  assets/js/std-progress.js
  assets/js/teach-ajax-addatt.js
  assets/js/teach-att.js
  assets/js/teach-carousel.js
  views/admin/addstudent.ejs
  views/admin/addteacher.ejs
  views/admin/allotsubjectform.ejs
  views/admin/dashboard.ejs
  views/student/attendance_view.ejs
  views/student/dashboard.ejs
  views/student/feedback_response.ejs
  views/teacher/dashboard.ejs
  views/teacher/subject/attendance-add.ejs
  views/teacher/subject/attendance-update.ejs
  views/teacher/subject/attendance-view.ejs
  views/teacher/subject/attendanceviewsingle.ejs
  views/teacher/subject/internalmarks.ejs
Labels: Rename

#92 v0.21.5: Teacher side pages rem -> vw vh
  assets/css/general.css
  assets/css/navbar.css
  assets/css/teach-allot-student-1.css
  assets/css/teach-allot-student-2.css
  assets/css/teach-assign-check.css
  assets/css/teach-att-add-update.css
  assets/css/teach-att-view.css
  assets/css/teach-dash.css
  assets/css/teach-general-att.css
  assets/css/teach-int.css
  assets/scss/general.scss
  assets/scss/navbar.scss
  assets/scss/teach-allot-student-1.scss
  assets/scss/teach-allot-student-2.scss
  assets/scss/teach-assign-check.scss
  assets/scss/teach-att-add-update.scss
  assets/scss/teach-att-view.scss
  assets/scss/teach-dash.scss
  assets/scss/teach-general-att.scss
  assets/scss/teach-int.scss
  assets/scss/teach-res-analysis.scss
  views/teacher/dashboard.ejs
Labels: Rename

#93 v0.22.2: Settings Page Added
  assets/scss/teacher-attendence.css
  assets/scss/teacher-settings.css
  views/template/settings-all.html
  views/template/settings.html
Labels: Page Added

#96 v0.26.1 addSection page added
  assets/scss/addSection.css
  views/admin/addSection.html
Labels: Page Added

#100 v0.28.5:admin's feedback not submitted page created
  assets/scss/teacher-settings.css
  views/template/settings.html
Labels: Page Added

#101 v0.28.7: Teacher Profile created, Spotlight Search linked w Profile P…
  assets/css/admin-addProgram.css
  assets/css/admin-dash.css
  assets/css/admin-sem.css
  assets/css/general.css
  assets/css/profile.css
  assets/css/std-dash-media.css
  assets/css/std-dash.css
  assets/css/teach-allot-student-1.css
  assets/css/teach-general-att.css
  assets/css/teach-profile.css
  assets/css/teach-res-analysis.css
  assets/scss/admin-addDept.scss
  assets/scss/admin-addProgram.scss
  assets/scss/admin-dash.scss
  assets/scss/general.scss
  assets/scss/profile.scss
  assets/scss/teach-profile.scss
  controllers/admin_controller.js
  controllers/teacher_controller.js
  routes/admins.js
  routes/teachers.js
  views/admin/addDepartment.ejs
  views/admin/admin-create-sem.ejs
  views/admin/allotsubject.ejs
  views/admin/dashboard.ejs
  views/student/profile.ejs
  views/teacher/profile-teach.ejs
  views/template/not-submitted.html
Labels: Page Added, Feature Added, Minor Bug Fixed

#103 v0.28.13: Examcell's dashboard, creat sub, cgpa&backlogs pages created
  assets/css/addSection.css
  assets/css/admin-add.css
  assets/css/admin-addDept.css
  assets/css/admin-addProgram.css
  assets/css/admin-allot-sub.css
  assets/css/admin-allottg.css
  assets/css/admin-cal.css
  assets/css/admin-dash.css
  assets/css/admin-noty.css
  assets/css/admin-sem.css
  assets/css/error.css
  assets/css/exam-cgpa-backlog.css
  assets/css/exam-create-sub.css
  assets/css/exam-dash.css
  assets/css/general.css
  assets/css/notes.css
  assets/css/profile.css
  assets/css/settings.css
  assets/css/signup.css
  assets/css/std-dash-media.css
  assets/css/std-dash.css
  assets/css/teach-assign-check.css
  assets/css/teach-note-popup.css
  assets/css/teach-profile.css
  assets/css/teach-res-analysis.css
  assets/scss/admin-allot-sub.scss
  assets/scss/exam-cgpa-backlog.scss
  assets/scss/exam-create-sub.scss
  assets/scss/exam-dash.scss
  assets/scss/general.scss
  upload/studentsProfile/documents/avatar-1689826164919-38368151
  upload/studentsProfile/documents/avatar-1689826483911-14246645
  upload/studentsProfile/documents/avatar-1689826605086-516952752
  upload/studentsProfile/documents/avatar-1689826681310-682017462
  upload/studentsProfile/documents/avatar-1689827099512-451707643
  views/admin/allotsubject.ejs
  views/admin/allotsubjectform.ejs
  views/examcell/cform.ejs
  views/examcell/cgpabacklog.ejs
  views/examcell/createsubject.ejs
  views/examcell/dashboard.ejs
  views/student/profile.ejs
  views/teacher/dashboard.ejs
Labels: Page Added

#104 v0.28.14: Lock Internals and Deactivate Page created
  assets/css/admin-dash.css
  assets/css/admin-deactivate.css
  assets/css/exam-create-sub.css
  assets/css/exam-lock-int.css
  assets/css/general.css
  assets/scss/admin-deactivate.scss
  assets/scss/exam-create-sub.scss
  assets/scss/exam-lock-int.scss
  assets/scss/general.scss
  controllers/admin_controller.js
  routes/admins.js
  views/admin/deactivate-accnt.ejs
  views/examcell/createsubject.ejs
  views/examcell/lockinternal.ejs
Labels: Page Added

#105 v0.28.15: Admin's View Feedback Page Created
  assets/css/teach-res-analysis.css
  assets/scss/admin-feedback.css
  views/admin/admin-feedback.html
Labels: Page Added

#115 v0.30.10: Admin Report Added
  assets/css/admin-sem.css
  assets/css/error.css
  assets/css/mail.css
  assets/scss/admin-sem.scss
  assets/scss/mail.scss
  controllers/admin_controller.js
  views/admin/report.ejs
  views/student/report.ejs
Labels: Page Added

#117 v0.30.12: mail and reports minor css bug fixed
  assets/css/addSection.css
  assets/css/mail.css
  assets/scss/mail.scss
  views/admin/mail.ejs
  views/student/report.ejs
Labels: Minor Bug Fixed

#118 v0.30.14: Developer's Page created
  .DS_Store
  assets/.DS_Store
  assets/css/developer.css
  assets/css/login.css
  assets/css/navbar.css
  assets/images/.DS_Store
  assets/images/dot-circle.png
  assets/images/man.png
  assets/images/nexus-vector.png
  assets/scss/developer.scss
  assets/scss/login.scss
  assets/scss/navbar.scss
  controllers/home_controller.js
  routes/index.js
  views/layout.ejs
  views/login-signup/Login.ejs
  views/login-signup/developer.ejs
  views/navbar/admin.ejs
  views/navbar/examcell.ejs
  views/navbar/feecell.ejs
  views/navbar/student.ejs
  views/navbar/teacher.ejs
Labels: Page Added
